grafana:
  admin:
    existingSecret: grafana  # Name of the secret for admin credentials
    adminPasswordKey: admin.password  # Key in the secret for the Grafana password

  sidecar:
    dashboards:
      enabled: true
      label: grafana-dashboard           # Label for ConfigMaps containing dashboards
      folder: /var/lib/grafana/dashboards  # Directory for storing dashboards in Grafana
      updateIntervalSeconds: 10          # Interval for updating dashboards
      folderAnnotation: grafana_folder    # Annotation for organizing dashboards into folders
      provider:
        allowUiUpdates: true             # Permit users to update dashboards via the UI
        foldersFromFilesStructure: true   # Use folder structure for organizing dashboards

  dashboardsConfigMaps:
    default: "grafana-dashboard"  